const nodemailer = require('nodemailer');
const dotenv = require('dotenv');

dotenv.config();

function mail(toMail, text, subject, htmlMessage) {
  const transport = nodemailer.createTransport({
    service: 'gmail',
    //   host: 'smtp.mailtrap.io',
    //   port: 2525,
    auth: {
      user: process.env.MAIL_USERNAME, //generated by Mailtrap
      pass: process.env.MAIL_PASSWORD, //generated by Mailtrap
    },
  });

  const mailOptions = {
    from: '"Basis Team" <chaitanya1019@gmail.com>',
    to: toMail,
    subject: subject,
    html: htmlMessage,
  };

  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
  });
}

module.exports = mail;
